### ISSUE TITLE
Help is incorrect for types -t flag

### ISSUE THREAD

**Issue by alagalah** [kunickiaj/beer#2]
Error: invalid argument "New" for "-t, --issue-type" flag: New is not a valid JIRA issue type
Usage:
  beer brew [flags]

Flags:
...
  -t, --issue-type [New Feature Task Improvement Bug]   Issue type to create

FATA[0000] Fatal Error                                   error="invalid argument \"New\" for \"-t, --issue-type\" flag: New is not a valid JIRA issue type"

➜ beer brew -t "New Feature"  ...

FATA[0000]                                               error="could not find issuetype New Feature, available types are []string{\"Task\", \"Sub-task\", \"Story\", \"Bug\", \"Epic\", \"Integration Test\"}"

**Comment by kunickiaj** [comment]
Thanks, yeah the help string seems to be hardcoded as a hint for one of the types of projects we use. I can remove that. The error message will show the actual available projects for the currently selected project.

**Comment by kunickiaj** [comment]
Fixed in v0.2.1
